CREATE TABLE reviews (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    comment VARCHAR(1000) NOT NULL,
    product_id BIGINT NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
